fix ssh_copy_id to re-add minis and make sure sshpass is installed before it's needed

diff --git a/cm/.chezmoiscripts/run_05_hosts_ssh_copy_id_all.sh.tmpl b/cm/.chezmoiscripts/run_05_hosts_ssh_copy_id_all.sh.tmpl
--- a/cm/.chezmoiscripts/run_05_hosts_ssh_copy_id_all.sh.tmpl
+++ b/cm/.chezmoiscripts/run_05_hosts_ssh_copy_id_all.sh.tmpl
@@ -9,6 +9,12 @@ if [ ! -f ~/.ssh/id_rsa ]; then
   ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
 fi
 
+# Check if sshpass command exists
+if ! command -v sshpass >/dev/null 2>&1; then
+  echo "sshpass not found, installing..."
+  sudo apt update && sudo apt install -y sshpass
+fi
+
 copy_id() {
   local host=$1
   local user=$2
@@ -22,7 +28,7 @@ copy_id() {
   fi
 }
 
-copy_id "chopin" "paul" "{{ (bitwarden "item" "homenetwork_chopin_paul").login.password }}"
+copy_id "minis" "paul" "{{ (bitwarden "item" "homenetwork_minis_paul").login.password }}"
 copy_id "rone" "paul" "{{ (bitwarden "item" "homenetwork_rone_paul").login.password }}"
 copy_id "ronewg" "paul" "{{ (bitwarden "item" "homenetwork_rone_paul").login.password }}"
 copy_id "10.0.0.3" "paul" "{{ (bitwarden "item" "homenetwork_rone_paul").login.password }}"
